version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/laioffer/Around
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t siqili/around .
          docker login -u="$siqili" -p="$Lsq941226_"
          docker push siqili/around
